FROM python:3.11-slim

WORKDIR /app


RUN mkdir -p /app/tempFiles

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Run the Celery worker
CMD ["celery", "-A", "app.celery_worker.app", "worker", "--loglevel=info"]
