version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    platform: linux
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    volumes:
      - shared-data:/app/tempFiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
    platform: linux

  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    volumes:
      - shared-data:/app/tempFiles
    depends_on:
      - redis
    platform: linux

volumes:
  shared-data:
