"""fcm messageId add

Revision ID: 2166292a287c
Revises: e1c56093c410
Create Date: 2024-06-30 12:23:55.106002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2166292a287c'
down_revision = 'e1c56093c410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_message_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_column('fcm_message_id')

    # ### end Alembic commands ###
