"""Initial migration.

Revision ID: e1c56093c410
Revises: 
Create Date: 2024-06-30 11:34:46.789574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1c56093c410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('coupon', sa.String(length=50), nullable=True),
    sa.Column('device_token', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('slack_bots', schema=None) as batch_op:
        batch_op.drop_index('slack_bots_idx')

    op.drop_table('slack_bots')
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_created_at')
        batch_op.drop_index('ix_chat_session_id')
        batch_op.drop_index('ix_chat_updated_at')

    op.drop_table('chat')
    with op.batch_alter_table('slack_installations', schema=None) as batch_op:
        batch_op.drop_index('slack_installations_idx')

    op.drop_table('slack_installations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_installations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('app_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('enterprise_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('enterprise_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('enterprise_url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('team_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('team_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bot_token', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bot_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('bot_user_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('bot_scopes', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('bot_refresh_token', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bot_token_expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_token', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('user_scopes', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('user_refresh_token', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('user_token_expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('incoming_webhook_url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('incoming_webhook_channel', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('incoming_webhook_channel_id', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('incoming_webhook_configuration_url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('is_enterprise_install', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('token_type', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('installed_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('slack_installations', schema=None) as batch_op:
        batch_op.create_index('slack_installations_idx', ['client_id', 'enterprise_id', 'team_id', 'user_id', 'installed_at'], unique=False)

    op.create_table('chat',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('author_role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('content_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('meta', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_index('ix_chat_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_chat_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_chat_created_at', ['created_at'], unique=False)

    op.create_table('slack_bots',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('app_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('enterprise_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('enterprise_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('team_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('team_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bot_token', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bot_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('bot_user_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('bot_scopes', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('bot_refresh_token', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bot_token_expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_enterprise_install', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('installed_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('slack_bots', schema=None) as batch_op:
        batch_op.create_index('slack_bots_idx', ['client_id', 'enterprise_id', 'team_id', 'installed_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_customer_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
